name: Test

on: [push, pull_request]

jobs:
  linux:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -qq libuv1-dev -y
        python -m pip install --upgrade pip
        pip install mys
    - name: Test
      run: |
        mys test
        mys -C examples/files_and_folders run

  macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        brew install libuv
        python -m pip install --upgrade pip
        pip install mys
    - name: Test
      run: |
        mys test

  release:
    needs: [linux, macos]
    runs-on: ubuntu-20.04
    if: startsWith(github.ref, 'refs/tags')

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mys
    - name: Publish release to mys-lang.org
      run: |
        mys publish -t ${{secrets.publish_token}}
